language: java
sudo: false

os:
  - linux
  - osx

jdk:
  - oraclejdk8
  - oraclejdk9

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build

cache:
  directories:
    - '$HOME/.gradle'
    - '.gradle'