language: java
sudo: false

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk9
    - os: osx
      osx_image: xcode9.3

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build

cache:
  directories:
    - '$HOME/.gradle'
    - '.gradle'